name: weatherapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  date_format: ^2.0.5
  sqflite: ^2.0.2
  path: ^1.8.0
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
